Tracking OPC fees
oceanprotocol/ocean-subgraph pull request #593
Opened 2023-01-03 16:37 UTC by jamiehewitt15

Fixes # .

Changes proposed in this PR:

- 
- 
-

2023-01-04 16:11 UTC, alexcos20 requested changes

2023-01-04 16:11 UTC, alexcos20 commented on src/mappings/fixedRateExchange.ts
> +    BigInt.fromI32(18).toI32()
OPF Fee is always taken in baseToken, so it's not always using 18 decimals.
You should use something like:
```
swap.oceanFeeAmount= weiToDecimal(
    event.params.oceanFeeAmount.toBigDecimal(),
    BigInt.fromI32(baseToken.decimals).toI32()
  )
  ```
  and move this code after we have baseToken  (like before swap.save() )

2023-01-10 15:55 UTC, alexcos20 requested changes

2023-01-10 17:41 UTC, jamiehewitt15 commented on test/integration/FixedRateExchange.test.ts
> +    assert(swaps.oceanFeeAmount === oceanFeeAmount, 'incorrect: oceanFeeAmount')
Yeah good point. I've updated this, thanks for the feedback

2023-01-11 06:35 UTC, alexcos20 approved these changes

2023-01-11 07:17 UTC, alexcos20 commented
I know that original issue was about OPFC fees, but let's add marketFeeAmount and consumeMarketFeeAmount as well

2023-01-12 11:51 UTC, jamiehewitt15 commented
> I know that original issue was about OPFC fees, but let's add marketFeeAmount and consumeMarketFeeAmount as well

@alexcos20 I've added them, can you let me know if you're happy with the changes?

2023-01-17 11:17 UTC, alexcos20 commented
lgtm, we can merge it
Thanks

2023-01-17 11:57 UTC, merged